# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: salvador19marti@gmail.com
author_name: Skymont
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: tracking-test
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension that gets extra telemetry data
python_name: tracking_test
repository: https://github.com/TheClassyPenguin/tracking-test.git
test: true
viewer_name: ''

